### PR TITLE
fixed typing mistake

### PR DESCRIPTION
**Pull request by freddii**

### CODE REVIEW

**Review by vonschutter — CHANGES_REQUESTED** [review]
hi Freddie, appreciate the review! I am not used to working with GitHub much and simply did not see your request. Between then an now I have changes some things. I have moved the recipe configuration from the "desktop" gui choice to a built in server choice using 'dialog' (in _rtd_library). Perhaps i should add "server_recipe" to the software recipe book too, or a separate book? Not sure...

**Review by vonschutter — APPROVED** [review]

**Comment by freddii** [comment]
I can close this pull request and open a new one if you like. Cause i deleted my source repo.

**Comment by vonschutter** [comment]
Sure, do that.

If you have any suggestions please do not hesitate to mention.


Kind regards
___________________
)
¸.·´¸.·*´¨)
(¸.·´ (¸. Stephan


Stephan Schutter

Cell:     +46 70 641 3983
Profile: http://www.linkedin.com/in/stephanschutter
Email:  stephan.schutter@gmail.com



This message is for the designated recipient only and may contain
privileged, proprietary, or otherwise private information. If you have
received it in error, please notify the sender immediately and delete the
original. Any other use of the email by you is prohibited.

**Comment by freddii** [comment]
created a new pull request at https://github.com/vonschutter/RTD-Build/pull/2

**Pull request closed without merging**
