### PR TITLE
fixed spelling mistakes

### PR DESCRIPTION
**Pull request by freddii**

### CODE REVIEW

**Review by vonschutter — APPROVED** [review]

**Comment by vonschutter** [comment]
deleted System_Setup/_rtd_functions

**Comment by freddii** [comment]
so how can i help resolving these conflicts?

**Comment by freddii** [comment]
should be fixed now.

**Comment by vonschutter** [comment]
I think it's OK now. I am not sure how the merges work exactly. I had to
reinitialize everything because I got confused with what was what and made
some kind of loop I could not get out of.

I thought if I clicked "approve" it would seamlessly merge... but I guess I
have changed the files too much?

I am not really a developer as you probably can tell... :) I have been a
sysadmin for years and found it fun to write scripts that do
useful things.  For instance: the rtd-simple-support-tool can spin up a VM
for windows, debian and Ubuntu... complete with auto unattend and preseed.


Kind regards
___________________
)
¸.·´¸.·*´¨)
(¸.·´ (¸. Stephan


Stephan Schutter

Cell:     +46 70 641 3983
Profile: http://www.linkedin.com/in/stephanschutter
Email:  stephan.schutter@gmail.com



This message is for the designated recipient only and may contain
privileged, proprietary, or otherwise private information. If you have
received it in error, please notify the sender immediately and delete the
original. Any other use of the email by you is prohibited.

**Pull request closed without merging**
